import React from 'react';
import { FileText, Download, ExternalLink, Calendar, CheckCircle, Clock } from 'lucide-react';
import type { ProjectReport } from '../../../types/ngo-projects';

interface ReportsTabProps {
  reports: ProjectReport[];
  onDownloadReport: (reportId: string, format: 'pdf' | 'docx') => void;
}

export function ReportsTab({ reports, onDownloadReport }: ReportsTabProps) {
  const getStatusConfig = (status: ProjectReport['status']) => {
    switch (status) {
      case 'approved':
        return { bg: 'bg-emerald-100', text: 'text-emerald-700', border: 'border-emerald-200', label: 'Approved', icon: CheckCircle };
      case 'under_review':
        return { bg: 'bg-amber-100', text: 'text-amber-700', border: 'border-amber-200', label: 'Under Review', icon: Clock };
      case 'revision_requested':
        return { bg: 'bg-rose-100', text: 'text-rose-700', border: 'border-rose-200', label: 'Revision Requested', icon: ExternalLink };
    }
  };

  const getTypeConfig = (type: ProjectReport['type']) => {
    return type === 'final'
      ? { bg: 'bg-indigo-100', text: 'text-indigo-700', label: 'Final Report' }
      : { bg: 'bg-slate-100', text: 'text-slate-700', label: 'Draft Report' };
  };

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  };

  const formatFileSize = (bytes: number) => {
    if (bytes >= 1024 * 1024) {
      return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    }
    return `${(bytes / 1024).toFixed(0)} KB`;
  };

  // Group reports by project
  const reportsByProject = reports.reduce((acc, report) => {
    if (!acc[report.project_title]) {
      acc[report.project_title] = [];
    }
    acc[report.project_title].push(report);
    return acc;
  }, {} as Record<string, ProjectReport[]>);

  if (reports.length === 0) {
    return (
      <div className="text-center py-16 bg-slate-50 rounded-xl border-2 border-dashed border-slate-200">
        <FileText className="w-16 h-16 text-slate-300 mx-auto mb-4" />
        <h3 className="text-slate-900 mb-2">No Reports Yet</h3>
        <p className="text-slate-600 max-w-md mx-auto">
          Reports will appear here once generated by Wasilah after your project updates are reviewed.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {Object.entries(reportsByProject).map(([projectTitle, projectReports]) => (
        <div key={projectTitle}>
          <h3 className="text-slate-900 mb-4">{projectTitle}</h3>
          <div className="space-y-4">
            {projectReports.map((report) => {
              const statusConfig = getStatusConfig(report.status);
              const typeConfig = getTypeConfig(report.type);
              const StatusIcon = statusConfig.icon;

              return (
                <div
                  key={report.id}
                  className="bg-white border-2 border-slate-200 rounded-xl p-6 hover:border-indigo-200 transition-colors"
                >
                  <div className="flex items-start justify-between gap-6">
                    {/* Left: Report Info */}
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-3">
                        <span className={`px-3 py-1 rounded-lg text-xs ${typeConfig.bg} ${typeConfig.text}`}>
                          {typeConfig.label}
                        </span>
                        <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-lg border-2 text-xs ${statusConfig.bg} ${statusConfig.text} ${statusConfig.border}`}>
                          <StatusIcon className="w-3 h-3" />
                          {statusConfig.label}
                        </span>
                      </div>

                      <div className="grid grid-cols-2 gap-4 mb-4">
                        <div>
                          <p className="text-xs text-slate-500 mb-0.5">Period Covered</p>
                          <p className="text-sm text-slate-900">
                            {formatDate(report.period_start)} - {formatDate(report.period_end)}
                          </p>
                        </div>
                        <div>
                          <p className="text-xs text-slate-500 mb-0.5">Generated</p>
                          <p className="text-sm text-slate-900">
                            {formatDate(report.generated_at)}
                          </p>
                        </div>
                      </div>

                      {/* Summary */}
                      <div className="grid grid-cols-4 gap-3 p-4 bg-slate-50 rounded-lg">
                        <div className="text-center">
                          <p className="text-lg text-slate-900">{report.summary.tasks_completed}</p>
                          <p className="text-xs text-slate-600">Tasks</p>
                        </div>
                        <div className="text-center">
                          <p className="text-lg text-slate-900">{report.summary.beneficiaries_reached.toLocaleString()}</p>
                          <p className="text-xs text-slate-600">Beneficiaries</p>
                        </div>
                        <div className="text-center">
                          <p className="text-lg text-slate-900">{report.summary.updates_included}</p>
                          <p className="text-xs text-slate-600">Updates</p>
                        </div>
                        <div className="text-center">
                          <p className="text-lg text-slate-900">{report.summary.media_count}</p>
                          <p className="text-xs text-slate-600">Media</p>
                        </div>
                      </div>

                      {/* Review Notes */}
                      {report.review_notes && (
                        <div className="mt-4 p-3 bg-blue-50 border-2 border-blue-200 rounded-lg">
                          <p className="text-xs text-blue-900">{report.review_notes}</p>
                        </div>
                      )}
                    </div>

                    {/* Right: Actions */}
                    <div className="flex flex-col gap-2 flex-shrink-0">
                      <button
                        onClick={() => onDownloadReport(report.id, 'pdf')}
                        className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors whitespace-nowrap"
                      >
                        <Download className="w-4 h-4" />
                        <span>PDF</span>
                      </button>
                      {report.file_url_docx && (
                        <button
                          onClick={() => onDownloadReport(report.id, 'docx')}
                          className="flex items-center gap-2 px-4 py-2 border-2 border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors whitespace-nowrap"
                        >
                          <Download className="w-4 h-4" />
                          <span>DOCX</span>
                        </button>
                      )}
                      <p className="text-xs text-slate-500 text-center mt-1">
                        {formatFileSize(report.file_size)}
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}