import React, { useState } from 'react';
import { 
  MapPin, Calendar, Users, TrendingUp, DollarSign, Target,
  MessageSquare, FileText, Plus, CheckCircle, Upload, 
  UserPlus, FileCheck, Banknote, Clock, Download
} from 'lucide-react';
import { Project, SDG_LIST } from '../../../types/projects';

interface OverviewTabProps {
  project: Project;
  onTabChange?: (tabId: 'overview' | 'ngos' | 'milestones' | 'volunteers' | 'finance' | 'impact') => void;
}

// Mock activity data
const MOCK_ACTIVITIES = [
  {
    id: '1',
    type: 'media',
    message: 'Al-Khidmat Foundation uploaded 12 photos',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    icon: Upload,
    color: 'bg-purple-100 text-purple-600'
  },
  {
    id: '2',
    type: 'volunteer',
    message: 'Sarah Ahmed applied as volunteer',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    icon: UserPlus,
    color: 'bg-blue-100 text-blue-600'
  },
  {
    id: '3',
    type: 'finance',
    message: 'Invoice #INV-2026-123 marked as paid',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    icon: Banknote,
    color: 'bg-green-100 text-green-600'
  },
  {
    id: '4',
    type: 'milestone',
    message: 'Milestone "Site preparation" completed',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    icon: CheckCircle,
    color: 'bg-teal-100 text-teal-600'
  },
  {
    id: '5',
    type: 'document',
    message: 'NGO verification documents approved',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    icon: FileCheck,
    color: 'bg-indigo-100 text-indigo-600'
  },
  {
    id: '6',
    type: 'volunteer',
    message: '5 new volunteer applications received',
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    icon: Users,
    color: 'bg-blue-100 text-blue-600'
  }
];

export function OverviewTab({ project, onTabChange }: OverviewTabProps) {
  const [isDescriptionExpanded, setIsDescriptionExpanded] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  
  const description = project.short_description || 'No description available';
  const shouldTruncate = description.length > 200;
  const displayDescription = shouldTruncate && !isDescriptionExpanded 
    ? description.substring(0, 200) + '...' 
    : description;

  // Calculate mock KPIs
  const volunteersEnrolled = Math.floor(project.volunteer_target * 0.53); // 53% enrolled
  const beneficiariesReached = Math.floor(project.volunteer_target * 4.2); // ~4.2 beneficiaries per volunteer
  const budgetSpent = Math.floor(project.budget * 0.55); // 55% spent
  const progressPercent = 54;

  // Calculate project duration and progress
  const startDate = new Date(project.start_date);
  const endDate = new Date(project.end_date);
  const today = new Date();
  const totalDays = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
  const daysPassed = Math.ceil((today.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
  const daysRemaining = Math.max(0, totalDays - daysPassed);

  const formatTimeAgo = (timestamp: string) => {
    const now = Date.now();
    const diff = now - new Date(timestamp).getTime();
    const hours = Math.floor(diff / (1000 * 60 * 60));
    const days = Math.floor(diff / (1000 * 60 * 60 * 24));

    if (hours < 1) return 'Just now';
    if (hours < 24) return `${hours}h ago`;
    if (days === 1) return 'Yesterday';
    return `${days}d ago`;
  };

  const handleExportSummary = () => {
    setIsExporting(true);
    
    // Generate PDF content
    const pdfContent = `
PROJECT SUMMARY REPORT
Generated: ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}

PROJECT DETAILS
Title: ${project.title}
Type: ${project.type}
Status: ${project.status}
Location: ${project.location.city}, ${project.location.country}

TIMELINE
Start Date: ${startDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
End Date: ${endDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
Days Remaining: ${daysRemaining}
Progress: ${progressPercent}%

KEY METRICS
Volunteers: ${volunteersEnrolled} / ${project.volunteer_target}
Beneficiaries Reached: ${beneficiariesReached.toLocaleString()}
Budget: PKR ${budgetSpent.toLocaleString()} / ${project.budget.toLocaleString()} (55% spent)

DESCRIPTION
${description}

SDGs ALIGNED
${project.sdgs?.map(id => `${id}. ${SDG_LIST.find(s => s.id === id)?.name || 'SDG ' + id}`).join('\n') || 'None'}

---
Generated by Wasilah CSR Platform
    `.trim();

    // Create blob and download
    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.slug || 'project'}-summary-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setTimeout(() => setIsExporting(false), 1000);
  };

  return (
    <div className="space-y-6">
      {/* Project Summary */}
      <div>
        <h3 className="text-sm text-slate-700 mb-3">Project Description</h3>
        <div className="p-4 bg-slate-50 rounded-xl border-2 border-slate-200">
          <p className="text-sm text-slate-700 leading-relaxed">
            {displayDescription}
          </p>
          {shouldTruncate && (
            <button
              onClick={() => setIsDescriptionExpanded(!isDescriptionExpanded)}
              className="mt-2 text-sm text-teal-600 hover:text-teal-700 transition-colors"
            >
              {isDescriptionExpanded ? 'Show less' : 'Read more'}
            </button>
          )}
        </div>
      </div>

      {/* SDGs */}
      {project.sdgs && project.sdgs.length > 0 && (
        <div>
          <h3 className="text-sm text-slate-700 mb-3">UN Sustainable Development Goals</h3>
          <div className="flex flex-wrap gap-2">
            {project.sdgs.map(sdgId => {
              const sdg = SDG_LIST.find(s => s.id === sdgId);
              return (
                <div
                  key={sdgId}
                  className="flex items-center gap-2 px-3 py-2 bg-white border-2 border-slate-200 rounded-lg text-xs hover:border-teal-300 transition-colors"
                >
                  <div className="w-6 h-6 rounded bg-gradient-to-br from-teal-500 to-blue-500 flex items-center justify-center text-white flex-shrink-0">
                    {sdgId}
                  </div>
                  <span className="text-slate-700">{sdg?.name || `SDG ${sdgId}`}</span>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Timeline Visualization */}
      <div>
        <h3 className="text-sm text-slate-700 mb-3">Project Timeline</h3>
        <div className="p-4 bg-gradient-to-br from-slate-50 to-blue-50 rounded-xl border-2 border-slate-200">
          <div className="flex items-center justify-between mb-3 text-xs text-slate-600">
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4" />
              <span>
                {startDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
              </span>
            </div>
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4" />
              <span>{daysRemaining} days remaining</span>
            </div>
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4" />
              <span>
                {endDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
              </span>
            </div>
          </div>
          
          {/* Progress bar */}
          <div className="relative h-2 bg-slate-200 rounded-full overflow-hidden">
            <div 
              className="absolute h-full bg-gradient-to-r from-teal-500 to-blue-500 transition-all duration-500"
              style={{ width: `${progressPercent}%` }}
            />
          </div>
          
          <div className="mt-2 text-right">
            <span className="text-xs text-slate-600">{progressPercent}% complete</span>
          </div>
        </div>
      </div>

      {/* Key Stats Row */}
      <div>
        <h3 className="text-sm text-slate-700 mb-3">Key Metrics</h3>
        <div className="grid grid-cols-2 gap-3">
          {/* Volunteers */}
          <button 
            onClick={() => onTabChange?.('volunteers')}
            className="p-4 bg-white border-2 border-slate-200 rounded-xl hover:border-teal-300 transition-colors text-left group"
          >
            <div className="flex items-center gap-2 text-slate-600 mb-2">
              <Users className="w-4 h-4" />
              <span className="text-xs">Volunteers</span>
            </div>
            <p className="text-2xl text-slate-900 mb-1">
              {volunteersEnrolled} <span className="text-base text-slate-500">/ {project.volunteer_target}</span>
            </p>
            <div className="flex items-center gap-1 text-xs text-green-600">
              <TrendingUp className="w-3 h-3" />
              <span>+12 this week</span>
            </div>
          </button>

          {/* Beneficiaries */}
          <button 
            onClick={() => onTabChange?.('impact')}
            className="p-4 bg-white border-2 border-slate-200 rounded-xl hover:border-teal-300 transition-colors text-left"
          >
            <div className="flex items-center gap-2 text-slate-600 mb-2">
              <Target className="w-4 h-4" />
              <span className="text-xs">Beneficiaries</span>
            </div>
            <p className="text-2xl text-slate-900 mb-1">{beneficiariesReached.toLocaleString()}</p>
            <div className="flex items-center gap-1 text-xs text-green-600">
              <TrendingUp className="w-3 h-3" />
              <span>+8% vs target</span>
            </div>
          </button>

          {/* Budget */}
          <button 
            onClick={() => onTabChange?.('finance')}
            className="p-4 bg-white border-2 border-slate-200 rounded-xl hover:border-teal-300 transition-colors text-left"
          >
            <div className="flex items-center gap-2 text-slate-600 mb-2">
              <DollarSign className="w-4 h-4" />
              <span className="text-xs">Budget</span>
            </div>
            <p className="text-xl text-slate-900 mb-1">
              PKR {(budgetSpent / 1000).toFixed(0)}K <span className="text-sm text-slate-500">/ {(project.budget / 1000).toFixed(0)}K</span>
            </p>
            <div className="flex items-center gap-1 text-xs text-slate-600">
              <span>55% spent</span>
            </div>
          </button>

          {/* Progress */}
          <button 
            onClick={() => onTabChange?.('milestones')}
            className="p-4 bg-white border-2 border-slate-200 rounded-xl hover:border-teal-300 transition-colors text-left"
          >
            <div className="flex items-center gap-2 text-slate-600 mb-2">
              <CheckCircle className="w-4 h-4" />
              <span className="text-xs">Progress</span>
            </div>
            <p className="text-2xl text-slate-900 mb-1">{progressPercent}%</p>
            <div className="flex items-center gap-1 text-xs text-green-600">
              <TrendingUp className="w-3 h-3" />
              <span>On track</span>
            </div>
          </button>
        </div>
      </div>

      {/* Quick Activity Feed */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-sm text-slate-700">Recent Activity</h3>
          <button className="text-xs text-teal-600 hover:text-teal-700 transition-colors">
            View all
          </button>
        </div>
        
        <div className="space-y-3">
          {MOCK_ACTIVITIES.map(activity => {
            const Icon = activity.icon;
            return (
              <div 
                key={activity.id} 
                className="flex items-start gap-3 p-3 bg-white border-2 border-slate-200 rounded-lg hover:border-slate-300 transition-colors"
              >
                <div className={`w-8 h-8 rounded-lg ${activity.color} flex items-center justify-center flex-shrink-0`}>
                  <Icon className="w-4 h-4" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm text-slate-900">{activity.message}</p>
                  <p className="text-xs text-slate-500 mt-0.5">
                    {formatTimeAgo(activity.timestamp)}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Quick Actions */}
      <div>
        <h3 className="text-sm text-slate-700 mb-3">Quick Actions</h3>
        <div className="grid grid-cols-2 gap-3">
          <button className="flex items-center justify-center gap-2 px-4 py-3 bg-white border-2 border-slate-200 rounded-lg hover:border-teal-300 hover:bg-slate-50 transition-colors text-sm text-slate-700">
            <MessageSquare className="w-4 h-4" />
            <span>Message NGO</span>
          </button>
          
          <button className="flex items-center justify-center gap-2 px-4 py-3 bg-white border-2 border-slate-200 rounded-lg hover:border-teal-300 hover:bg-slate-50 transition-colors text-sm text-slate-700">
            <Plus className="w-4 h-4" />
            <span>Add Note</span>
          </button>
          
          <button 
            onClick={handleExportSummary}
            disabled={isExporting}
            className="col-span-2 flex items-center justify-center gap-2 px-4 py-3 bg-gradient-to-r from-teal-600 to-blue-600 text-white rounded-lg hover:shadow-lg transition-all text-sm disabled:opacity-50"
          >
            {isExporting ? (
              <>
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                <span>Generating...</span>
              </>
            ) : (
              <>
                <Download className="w-4 h-4" />
                <span>Export Summary</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Project Details */}
      <div>
        <h3 className="text-sm text-slate-700 mb-3">Project Details</h3>
        <div className="space-y-3">
          <div className="flex items-start gap-3 p-3 bg-slate-50 rounded-lg">
            <MapPin className="w-4 h-4 text-slate-600 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="text-xs text-slate-600 mb-0.5">Location</p>
              <p className="text-sm text-slate-900">{project.location.city}, {project.location.country}</p>
              {project.location.address && (
                <p className="text-xs text-slate-600 mt-1">{project.location.address}</p>
              )}
            </div>
          </div>

          <div className="flex items-start gap-3 p-3 bg-slate-50 rounded-lg">
            <FileText className="w-4 h-4 text-slate-600 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="text-xs text-slate-600 mb-0.5">Project Type</p>
              <p className="text-sm text-slate-900 capitalize">{project.type}</p>
            </div>
          </div>

          <div className="flex items-start gap-3 p-3 bg-slate-50 rounded-lg">
            <Users className="w-4 h-4 text-slate-600 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="text-xs text-slate-600 mb-0.5">Delivery Mode</p>
              <p className="text-sm text-slate-900 capitalize">{project.delivery_mode}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}