/**
 * Mock Search Data
 * Comprehensive searchable entities for demonstration
 * In production, this would come from an API/database
 */

import { SearchableEntity } from './types';

export const mockSearchData: SearchableEntity[] = [
  // Projects
  {
    id: 'proj-001',
    type: 'project',
    title: 'Rural Solar Electrification Program',
    description: 'Installing solar panels in 50 rural villages across Punjab to provide clean energy.',
    subtitle: 'Green Pakistan Initiative',
    category: 'Energy & Environment',
    status: 'Active',
    tags: ['SDG-7', 'Clean Energy', 'Rural Development', 'Climate Action'],
    metadata: { budget: 'PKR 12.5M', villages: 50, beneficiaries: 25000 },
  },
  {
    id: 'proj-002',
    type: 'project',
    title: 'Clean Water Well Installation',
    description: 'Building water wells and filtration systems in underserved communities.',
    subtitle: 'Clean Water Alliance',
    category: 'Water & Sanitation',
    status: 'Active',
    tags: ['SDG-6', 'Water Access', 'Health', 'Rural Development'],
    metadata: { budget: 'PKR 8.2M', wells: 30, beneficiaries: 15000 },
  },
  {
    id: 'proj-003',
    type: 'project',
    title: 'Girls Education Initiative - Sindh',
    description: 'Scholarship program and school infrastructure for girls in rural Sindh.',
    subtitle: 'Education First Pakistan',
    category: 'Education',
    status: 'Active',
    tags: ['SDG-4', 'Education', 'Gender Equality', 'Youth Development'],
    metadata: { budget: 'PKR 15M', schools: 20, students: 5000 },
  },
  {
    id: 'proj-004',
    type: 'project',
    title: 'Urban Tree Plantation Drive',
    description: 'Planting 100,000 trees across Karachi, Lahore, and Islamabad.',
    subtitle: 'Green Pakistan Initiative',
    category: 'Environment',
    status: 'Completed',
    tags: ['SDG-13', 'Climate Action', 'Urban Development', 'Environment'],
    metadata: { budget: 'PKR 4.5M', trees: 100000, cities: 3 },
  },
  {
    id: 'proj-005',
    type: 'project',
    title: 'Women Entrepreneurship Program',
    description: 'Microfinance and training for women-led small businesses.',
    subtitle: 'Economic Empowerment Foundation',
    category: 'Economic Development',
    status: 'Active',
    tags: ['SDG-5', 'SDG-8', 'Women Empowerment', 'Economic Growth'],
    metadata: { budget: 'PKR 6M', participants: 500, businesses: 200 },
  },

  // NGOs
  {
    id: 'ngo-001',
    type: 'ngo',
    title: 'Green Pakistan Initiative',
    description: 'Leading environmental NGO focused on climate action and renewable energy.',
    subtitle: 'Environmental Organization',
    category: 'Environment',
    status: 'Verified',
    tags: ['Climate Change', 'Renewable Energy', 'Conservation'],
    metadata: { founded: 2015, projects: 45, volunteers: 2500, sdgs: ['SDG-7', 'SDG-13'] },
  },
  {
    id: 'ngo-002',
    type: 'ngo',
    title: 'Education First Pakistan',
    description: 'Providing quality education access to underprivileged children.',
    subtitle: 'Education NGO',
    category: 'Education',
    status: 'Verified',
    tags: ['Education', 'Youth Development', 'Literacy'],
    metadata: { founded: 2012, projects: 38, volunteers: 1800, sdgs: ['SDG-4'] },
  },
  {
    id: 'ngo-003',
    type: 'ngo',
    title: 'Clean Water Alliance',
    description: 'Ensuring safe drinking water access for rural communities.',
    subtitle: 'Water & Sanitation NGO',
    category: 'Water & Sanitation',
    status: 'Verified',
    tags: ['Water Access', 'Public Health', 'Rural Development'],
    metadata: { founded: 2018, projects: 22, volunteers: 800, sdgs: ['SDG-6'] },
  },
  {
    id: 'ngo-004',
    type: 'ngo',
    title: 'Healthcare for All Foundation',
    description: 'Mobile clinics and health services for underserved populations.',
    subtitle: 'Healthcare NGO',
    category: 'Healthcare',
    status: 'Verified',
    tags: ['Healthcare', 'Medical Services', 'Public Health'],
    metadata: { founded: 2010, projects: 52, volunteers: 3200, sdgs: ['SDG-3'] },
  },
  {
    id: 'ngo-005',
    type: 'ngo',
    title: 'Climate Action Pakistan',
    description: 'Youth-led organization fighting climate change through advocacy and action.',
    subtitle: 'Climate NGO',
    category: 'Environment',
    status: 'Pending Review',
    tags: ['Climate Change', 'Youth Activism', 'Advocacy'],
    metadata: { founded: 2022, projects: 8, volunteers: 450, sdgs: ['SDG-13'] },
  },

  // Volunteers
  {
    id: 'vol-001',
    type: 'volunteer',
    title: 'Sarah Ahmed',
    description: 'Environmental engineer passionate about renewable energy projects.',
    subtitle: 'Senior Volunteer - 250 hours contributed',
    category: 'Environment',
    status: 'Active',
    tags: ['Engineering', 'Solar Energy', 'Project Management'],
    metadata: { skills: ['Engineering', 'Solar', 'Leadership'], hours: 250, projects: 12 },
  },
  {
    id: 'vol-002',
    type: 'volunteer',
    title: 'Ahmed Khan',
    description: 'Teacher dedicated to education initiatives in rural areas.',
    subtitle: 'Active Volunteer - 180 hours contributed',
    category: 'Education',
    status: 'Active',
    tags: ['Teaching', 'Education', 'Rural Development'],
    metadata: { skills: ['Teaching', 'Curriculum', 'Mentoring'], hours: 180, projects: 8 },
  },
  {
    id: 'vol-003',
    type: 'volunteer',
    title: 'Fatima Malik',
    description: 'Medical student organizing health camps and awareness programs.',
    subtitle: 'Active Volunteer - 320 hours contributed',
    category: 'Healthcare',
    status: 'Active',
    tags: ['Healthcare', 'Medicine', 'Community Service'],
    metadata: { skills: ['Healthcare', 'First Aid', 'Education'], hours: 320, projects: 15 },
  },

  // Opportunities
  {
    id: 'opp-001',
    type: 'opportunity',
    title: 'Solar Panel Installation Volunteers Needed',
    description: 'Help install solar panels in rural Punjab villages. Training provided.',
    subtitle: 'Green Pakistan Initiative • Lahore',
    category: 'Environment',
    status: 'Open',
    tags: ['Solar Energy', 'Engineering', 'Rural Development'],
    metadata: { positions: 20, duration: '3 months', commitment: 'Full-time' },
  },
  {
    id: 'opp-002',
    type: 'opportunity',
    title: 'Teaching Assistant - Girls School',
    description: 'Support teachers in rural girls schools. Previous teaching experience preferred.',
    subtitle: 'Education First Pakistan • Sindh',
    category: 'Education',
    status: 'Open',
    tags: ['Teaching', 'Education', 'Women Empowerment'],
    metadata: { positions: 10, duration: '6 months', commitment: 'Part-time' },
  },
  {
    id: 'opp-003',
    type: 'opportunity',
    title: 'Water Quality Testing Volunteers',
    description: 'Conduct water quality tests and community education on water safety.',
    subtitle: 'Clean Water Alliance • Multiple Locations',
    category: 'Water & Sanitation',
    status: 'Open',
    tags: ['Water Testing', 'Science', 'Community Education'],
    metadata: { positions: 8, duration: '2 months', commitment: 'Flexible' },
  },
  {
    id: 'opp-004',
    type: 'opportunity',
    title: 'Health Camp Organizers',
    description: 'Organize and manage mobile health camps in underserved areas.',
    subtitle: 'Healthcare for All Foundation • Karachi',
    category: 'Healthcare',
    status: 'Urgent',
    tags: ['Healthcare', 'Event Management', 'Community Service'],
    metadata: { positions: 15, duration: '1 month', commitment: 'Weekend' },
  },

  // Corporates
  {
    id: 'corp-001',
    type: 'corporate',
    title: 'Engro Corporation',
    description: 'Leading Pakistani conglomerate with strong CSR focus on education and energy.',
    subtitle: 'Corporate Partner - Platinum Tier',
    category: 'Energy & Manufacturing',
    status: 'Active Partner',
    tags: ['CSR', 'Education', 'Energy', 'Agriculture'],
    metadata: { csrBudget: 'PKR 500M', projects: 28, impactScore: 95 },
  },
  {
    id: 'corp-002',
    type: 'corporate',
    title: 'Unilever Pakistan',
    description: 'FMCG leader committed to sustainable development and community welfare.',
    subtitle: 'Corporate Partner - Platinum Tier',
    category: 'Consumer Goods',
    status: 'Active Partner',
    tags: ['CSR', 'Sustainability', 'Health', 'Water'],
    metadata: { csrBudget: 'PKR 350M', projects: 35, impactScore: 92 },
  },
  {
    id: 'corp-003',
    type: 'corporate',
    title: 'HBL - Habib Bank Limited',
    description: 'Pakistan\'s largest bank with extensive CSR programs in education and healthcare.',
    subtitle: 'Corporate Partner - Gold Tier',
    category: 'Banking & Finance',
    status: 'Active Partner',
    tags: ['CSR', 'Financial Inclusion', 'Education', 'Healthcare'],
    metadata: { csrBudget: 'PKR 280M', projects: 22, impactScore: 88 },
  },

  // Payments
  {
    id: 'pay-001',
    type: 'payment',
    title: 'Payment to Green Pakistan Initiative - Q1 2026',
    description: 'Quarterly disbursement for Solar Electrification Program.',
    subtitle: 'PKR 3,125,000 • Completed',
    category: 'Project Funding',
    status: 'Completed',
    tags: ['Disbursement', 'Q1 2026', 'Solar Project'],
    metadata: { amount: 3125000, date: '2026-01-02', project: 'proj-001' },
  },
  {
    id: 'pay-002',
    type: 'payment',
    title: 'Payment Hold - Education First Pakistan',
    description: 'Payment hold pending document verification for Girls Education Initiative.',
    subtitle: 'PKR 850,000 • On Hold',
    category: 'Project Funding',
    status: 'Hold',
    tags: ['Hold', 'Pending Review', 'Education'],
    metadata: { amount: 850000, holdReason: 'Document verification', project: 'proj-003' },
  },

  // Users
  {
    id: 'user-001',
    type: 'user',
    title: 'Admin - Ahmed Khan',
    description: 'Platform Administrator with full system access.',
    subtitle: 'admin@wasilah.pk • Super Admin',
    category: 'Administration',
    status: 'Active',
    tags: ['Admin', 'Full Access', 'System'],
    metadata: { role: 'Super Admin', lastLogin: '2026-01-03', permissions: 'all' },
  },
  {
    id: 'user-002',
    type: 'user',
    title: 'NGO Manager - Fatima Hassan',
    description: 'NGO Partnership Manager handling vetting and onboarding.',
    subtitle: 'fatima.hassan@wasilah.pk • NGO Manager',
    category: 'Administration',
    status: 'Active',
    tags: ['NGO Management', 'Vetting', 'Partnerships'],
    metadata: { role: 'NGO Manager', lastLogin: '2026-01-03', ngosManaged: 15 },
  },

  // Cases
  {
    id: 'case-001',
    type: 'case',
    title: 'Funding Dispute - Education First Pakistan',
    description: 'Dispute regarding milestone completion and fund release.',
    subtitle: 'CASE-005 • Escalated • High Priority',
    category: 'Dispute Resolution',
    status: 'Escalated',
    tags: ['Dispute', 'Funding', 'High Priority'],
    metadata: { caseId: 'CASE-005', priority: 'high', assignee: 'Ahmed Khan' },
  },
  {
    id: 'case-002',
    type: 'case',
    title: 'NGO Verification Issue - Climate Action Pakistan',
    description: 'Document verification issue during NGO vetting process.',
    subtitle: 'CASE-008 • Open • Medium Priority',
    category: 'Vetting',
    status: 'Open',
    tags: ['Vetting', 'Documentation', 'Medium Priority'],
    metadata: { caseId: 'CASE-008', priority: 'medium', assignee: 'Sarah Ahmed' },
  },
];
